version: '2'
services:
    opticalshopall-app:
        image: opticalshopall
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://opticalshopall-postgresql:5432/opticalshopall
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://opticalshopall-elasticsearch:9200
        ports:
            - 8080:8080
    opticalshopall-postgresql:
        extends:
            file: postgresql.yml
            service: opticalshopall-postgresql
    opticalshopall-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: opticalshopall-elasticsearch
